import {Color} from 'three-full'

const BACKGROUND_COLOR = new Color(0xcccce0)
const DEFAULT_ITEM_COLOR = new Color(0x666666)

const DIRECTIONAL_LIGHT_COLOR = new Color(0xffffff)

const AMBIENT_LIGHT_COLOR = new Color(0xffffff)
const AMBIENT_LIGHT_INTENSITY = 0.7

const CONTROLLER_COLOR = new Color(0x706666)

const HEMISPHERE_LIGHT_SKY_COLOR = new Color(0x000000)
const HEMISPHERE_LIGHT_GROUND_COLOR = new Color(0xffffff)
const HEMISPHERE_LIGHT_INTENSITY = 0.5

export {
    BACKGROUND_COLOR,
    DEFAULT_ITEM_COLOR,
    DIRECTIONAL_LIGHT_COLOR,
    AMBIENT_LIGHT_COLOR,
    AMBIENT_LIGHT_INTENSITY,
    CONTROLLER_COLOR,
    HEMISPHERE_LIGHT_SKY_COLOR,
    HEMISPHERE_LIGHT_GROUND_COLOR,
    HEMISPHERE_LIGHT_INTENSITY,
}
