const WORLD_SCALE_UNIT = 333

const ORTHOGRAPHIC_DISTANCE = 2 * WORLD_SCALE_UNIT

const PERSPECTIVE_FOV = 70
const PERSPECTIVE_ASPECT_RATIO = window.innerWidth / window.innerHeight
const PERSPECTIVE_FRUSTUM_NEAR = 0.01
const PERSPECTIVE_FRUSTUM_FAR = 3 * WORLD_SCALE_UNIT

const ORTHOGRAPHIC_FRUSTUM_LEFT = -ORTHOGRAPHIC_DISTANCE * window.innerWidth / window.innerHeight
const ORTHOGRAPHIC_FRUSTUM_RIGHT = ORTHOGRAPHIC_DISTANCE * window.innerWidth / window.innerHeight
const ORTHOGRAPHIC_FRUSTUM_TOP = ORTHOGRAPHIC_DISTANCE
const ORTHOGRAPHIC_FRUSTUM_BOTTOM = -ORTHOGRAPHIC_DISTANCE
const ORTHOGRAPHIC_FRUSTUM_NEAR = -1 * WORLD_SCALE_UNIT
const ORTHOGRAPHIC_FRUSTUM_FAR = 4 * WORLD_SCALE_UNIT

const DEFAULT_ITEM_POSITION = [0, 0, 0]
const DEFAULT_ITEM_SCALE = [1, 1, 1]
const DEFAULT_ITEM_ROTATION = [0, 0, 0]

const INITIAL_ORTHOGRAPHIC_POSITION = [WORLD_SCALE_UNIT, WORLD_SCALE_UNIT, WORLD_SCALE_UNIT]
const INITIAL_ORTHOGRAPHIC_TARGET = [0, 0, 0]

const HUMAN_HEIGHT = 1.6

const INITIAL_PERSPECTIVE_POSITION = [0, HUMAN_HEIGHT, 0]
const INITIAL_PERSPECTIVE_TARGET = [1, HUMAN_HEIGHT, 0]

const DIRECTIONAL_LIGHT_POSITION = [150.14214, 150.28427, 150.07107]

const FOG_NEAR = 10
const FOG_FAR = 5 * WORLD_SCALE_UNIT

const CONTROLLER_SCALE = [0.05, 0.05, 0.05]

const MOVEMENT_SPEED = 0.125
const ROTATION_SPEED = 0.0125

const COURTYARD_SIZE = 2 * WORLD_SCALE_UNIT

const MOVEMENT_EASING_TIME = 800

export {
    ORTHOGRAPHIC_DISTANCE,
    PERSPECTIVE_FOV,
    PERSPECTIVE_ASPECT_RATIO,
    PERSPECTIVE_FRUSTUM_NEAR,
    PERSPECTIVE_FRUSTUM_FAR,
    ORTHOGRAPHIC_FRUSTUM_LEFT,
    ORTHOGRAPHIC_FRUSTUM_RIGHT,
    ORTHOGRAPHIC_FRUSTUM_TOP,
    ORTHOGRAPHIC_FRUSTUM_BOTTOM,
    ORTHOGRAPHIC_FRUSTUM_NEAR,
    ORTHOGRAPHIC_FRUSTUM_FAR,
    DEFAULT_ITEM_POSITION,
    DEFAULT_ITEM_ROTATION,
    DEFAULT_ITEM_SCALE,
    INITIAL_ORTHOGRAPHIC_POSITION,
    INITIAL_ORTHOGRAPHIC_TARGET,
    INITIAL_PERSPECTIVE_POSITION,
    INITIAL_PERSPECTIVE_TARGET,
    DIRECTIONAL_LIGHT_POSITION,
    FOG_NEAR,
    FOG_FAR,
    CONTROLLER_SCALE,
    MOVEMENT_SPEED,
    ROTATION_SPEED,
    COURTYARD_SIZE,
    MOVEMENT_EASING_TIME,
}
